id: push_git
namespace: system

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    url: https://manojna191:{{ kv('password_git') }}@github.com/manojna191/Other-Side.git
    sourceNamespace: company.team
    targetNamespace: newsProcessing
    flows: "*"
    branch: main
    username: manojna191
    password: "{{ kv('password_git') }}"
    commitMessage: add namespace files changes

  - id: commit_and_push_files
    type: io.kestra.plugin.git.PushNamespaceFiles
    namespace: company.team
    files: "*"
    gitDirectory: _files
    url: https://manojna191:{{ kv('password_git') }}@github.com/manojna191/Other-Side.git # required string
    username: manojna191
    password: "{{ kv('password_git') }}"
    branch: main
    commitMessage: "add namespace files"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@hourly" # every hour