id: debezium-postgres
namespace: newsProcessing

tasks:
  - id: send_data
    type: io.kestra.plugin.core.log.Log
    message: "{{trigger.data}} #data is changed"

triggers:
  - id: realtime
    type: io.kestra.plugin.debezium.postgres.RealtimeTrigger
    database: postgres
    hostname: host.docker.internal
    port: 5432
    username: postgres
    password: mysecretpassword
    